#!/bin/bash

echo   ---Setting the install path in executable files---

echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat runEpitopeDB_neoepitopes.sh >>temp
mv temp runEpitopeDB_neoepitopes.sh

echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat run_neoepitopes.sh >>temp
mv temp run_neoepitopes.sh

echo ---Making files executable for all users---

#change permissions and add to path
chmod +x runEpitopeDB_neoepitopes.sh run_neoepitopes.sh
echo "PATH=\"`pwd`:\$PATH\"" >> ~/.bash_profile


echo ---Installing the julia packages from pkginstall.jl---

julia pkginstall.jl
