#!/bin/bash
#add paths to run file
echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat runEpitopeDB_neoepitopes.sh >>temp
mv temp runEpitopeDB_neoepitopes.sh

echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat run_neoepitopes.sh >>temp
mv temp run_neoepitopes.sh

#change permissions and add to path
chmod +x runEpitopeDB_neoepitopes.sh run_neoepitopes.sh
echo "PATH=\"`pwd`:\$PATH\"" >> ~/.bash_profile
