#!/bin/bash

echo ----------------------------------------------------
echo    Setting the install path in executable files  
echo ----------------------------------------------------

echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat runEpitopeDB_neoepitopes.sh >>temp
mv temp runEpitopeDB_neoepitopes.sh

echo \#\!/bin/bash > temp
echo path1=\"`pwd`\" >> temp
cat run_neoepitopes.sh >>temp
mv temp run_neoepitopes.sh

echo ----------------------------------------------------
echo    Grating permission to the executable files    
echo ----------------------------------------------------

#change permissions and add to path
chmod +x runEpitopeDB_neoepitopes.sh run_neoepitopes.sh
echo "PATH=\"`pwd`:\$PATH\"" >> ~/.bash_profile


echo ----------------------------------------------------
echo    Installing the julia packages in pkginstall.jl 
echo ----------------------------------------------------

julia pkginstall.jl
